//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace GtDev.SpeedCamera.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinManagerQuery", Namespace="http://tempuri.org/")]
    public partial class PinManagerQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BeforeField;
        
        private string guidField;
        
        private string AfterField;
        
        private string GroupTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Before {
            get {
                return this.BeforeField;
            }
            set {
                if ((object.ReferenceEquals(this.BeforeField, value) != true)) {
                    this.BeforeField = value;
                    this.RaisePropertyChanged("Before");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string After {
            get {
                return this.AfterField;
            }
            set {
                if ((object.ReferenceEquals(this.AfterField, value) != true)) {
                    this.AfterField = value;
                    this.RaisePropertyChanged("After");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GroupTitle {
            get {
                return this.GroupTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupTitleField, value) != true)) {
                    this.GroupTitleField = value;
                    this.RaisePropertyChanged("GroupTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.AjaxSoap")]
    public interface AjaxSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewPinGraphics", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsResponse> GetNewPinGraphicsAsync(GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPinGraphics", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsResponse> CheckPinGraphicsAsync(GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewPin", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinResponse> GetNewPinAsync(GtDev.SpeedCamera.ServiceReference.GetNewPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPin", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinResponse> CheckPinAsync(GtDev.SpeedCamera.ServiceReference.CheckPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVoite", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveVoiteResponse> SaveVoiteAsync(GtDev.SpeedCamera.ServiceReference.SaveVoiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveForum", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveForumResponse> SaveForumAsync(GtDev.SpeedCamera.ServiceReference.SaveForumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCache", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.PinManagerQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.ArrayOfString))]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetCacheResponse> GetCacheAsync(GtDev.SpeedCamera.ServiceReference.GetCacheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.PinManagerQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.ArrayOfString))]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetResponse> GetAsync(GtDev.SpeedCamera.ServiceReference.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExt", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.PinManagerQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GtDev.SpeedCamera.ServiceReference.ArrayOfString))]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetExtResponse> GetExtAsync(GtDev.SpeedCamera.ServiceReference.GetExtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhotoPages", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetPhotoPagesResponse> GetPhotoPagesAsync(GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddObjectAjax", ReplyAction="*")]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.AddObjectAjaxResponse> AddObjectAjaxAsync(GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPinGraphicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPinGraphics", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequestBody Body;
        
        public GetNewPinGraphicsRequest() {
        }
        
        public GetNewPinGraphicsRequest(GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewPinGraphicsRequestBody {
        
        public GetNewPinGraphicsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPinGraphicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPinGraphicsResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsResponseBody Body;
        
        public GetNewPinGraphicsResponse() {
        }
        
        public GetNewPinGraphicsResponse(GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewPinGraphicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewPinGraphicsResult;
        
        public GetNewPinGraphicsResponseBody() {
        }
        
        public GetNewPinGraphicsResponseBody(string GetNewPinGraphicsResult) {
            this.GetNewPinGraphicsResult = GetNewPinGraphicsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPinGraphicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPinGraphics", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequestBody Body;
        
        public CheckPinGraphicsRequest() {
        }
        
        public CheckPinGraphicsRequest(GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPinGraphicsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string txt;
        
        public CheckPinGraphicsRequestBody() {
        }
        
        public CheckPinGraphicsRequestBody(string txt) {
            this.txt = txt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPinGraphicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPinGraphicsResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsResponseBody Body;
        
        public CheckPinGraphicsResponse() {
        }
        
        public CheckPinGraphicsResponse(GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPinGraphicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckPinGraphicsResult;
        
        public CheckPinGraphicsResponseBody() {
        }
        
        public CheckPinGraphicsResponseBody(bool CheckPinGraphicsResult) {
            this.CheckPinGraphicsResult = CheckPinGraphicsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPin", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetNewPinRequestBody Body;
        
        public GetNewPinRequest() {
        }
        
        public GetNewPinRequest(GtDev.SpeedCamera.ServiceReference.GetNewPinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewPinRequestBody {
        
        public GetNewPinRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPinResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetNewPinResponseBody Body;
        
        public GetNewPinResponse() {
        }
        
        public GetNewPinResponse(GtDev.SpeedCamera.ServiceReference.GetNewPinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewPinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GtDev.SpeedCamera.ServiceReference.PinManagerQuery GetNewPinResult;
        
        public GetNewPinResponseBody() {
        }
        
        public GetNewPinResponseBody(GtDev.SpeedCamera.ServiceReference.PinManagerQuery GetNewPinResult) {
            this.GetNewPinResult = GetNewPinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPin", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.CheckPinRequestBody Body;
        
        public CheckPinRequest() {
        }
        
        public CheckPinRequest(GtDev.SpeedCamera.ServiceReference.CheckPinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string txt;
        
        public CheckPinRequestBody() {
        }
        
        public CheckPinRequestBody(string guid, string txt) {
            this.guid = guid;
            this.txt = txt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPinResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.CheckPinResponseBody Body;
        
        public CheckPinResponse() {
        }
        
        public CheckPinResponse(GtDev.SpeedCamera.ServiceReference.CheckPinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckPinResult;
        
        public CheckPinResponseBody() {
        }
        
        public CheckPinResponseBody(bool CheckPinResult) {
            this.CheckPinResult = CheckPinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveVoiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveVoite", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.SaveVoiteRequestBody Body;
        
        public SaveVoiteRequest() {
        }
        
        public SaveVoiteRequest(GtDev.SpeedCamera.ServiceReference.SaveVoiteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveVoiteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string list;
        
        public SaveVoiteRequestBody() {
        }
        
        public SaveVoiteRequestBody(int GuidObject, string list) {
            this.GuidObject = GuidObject;
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveVoiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveVoiteResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.SaveVoiteResponseBody Body;
        
        public SaveVoiteResponse() {
        }
        
        public SaveVoiteResponse(GtDev.SpeedCamera.ServiceReference.SaveVoiteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveVoiteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveVoiteResult;
        
        public SaveVoiteResponseBody() {
        }
        
        public SaveVoiteResponseBody(int SaveVoiteResult) {
            this.SaveVoiteResult = SaveVoiteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveForumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveForum", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.SaveForumRequestBody Body;
        
        public SaveForumRequest() {
        }
        
        public SaveForumRequest(GtDev.SpeedCamera.ServiceReference.SaveForumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveForumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int GuidClassifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int GuidObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pin1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pin2;
        
        public SaveForumRequestBody() {
        }
        
        public SaveForumRequestBody(int GuidControl, int GuidClassifier, int GuidObject, string name, string title, string text, string pin1, string pin2) {
            this.GuidControl = GuidControl;
            this.GuidClassifier = GuidClassifier;
            this.GuidObject = GuidObject;
            this.name = name;
            this.title = title;
            this.text = text;
            this.pin1 = pin1;
            this.pin2 = pin2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveForumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveForumResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.SaveForumResponseBody Body;
        
        public SaveForumResponse() {
        }
        
        public SaveForumResponse(GtDev.SpeedCamera.ServiceReference.SaveForumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveForumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveForumResult;
        
        public SaveForumResponseBody() {
        }
        
        public SaveForumResponseBody(string SaveForumResult) {
            this.SaveForumResult = SaveForumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCache", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetCacheRequestBody Body;
        
        public GetCacheRequest() {
        }
        
        public GetCacheRequest(GtDev.SpeedCamera.ServiceReference.GetCacheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCacheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameCache;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object Param3;
        
        public GetCacheRequestBody() {
        }
        
        public GetCacheRequestBody(string NameCache, int GuidControl, object Param1, object Param2, object Param3) {
            this.NameCache = NameCache;
            this.GuidControl = GuidControl;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCacheResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetCacheResponseBody Body;
        
        public GetCacheResponse() {
        }
        
        public GetCacheResponse(GtDev.SpeedCamera.ServiceReference.GetCacheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCacheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCacheResult;
        
        public GetCacheResponseBody() {
        }
        
        public GetCacheResponseBody(string GetCacheResult) {
            this.GetCacheResult = GetCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(GtDev.SpeedCamera.ServiceReference.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object Param3;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(int GuidControl, object Param1, object Param2, object Param3) {
            this.GuidControl = GuidControl;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(GtDev.SpeedCamera.ServiceReference.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(string GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExt", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetExtRequestBody Body;
        
        public GetExtRequest() {
        }
        
        public GetExtRequest(GtDev.SpeedCamera.ServiceReference.GetExtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object Param3;
        
        public GetExtRequestBody() {
        }
        
        public GetExtRequestBody(int GuidControl, object Param1, object Param2, object Param3) {
            this.GuidControl = GuidControl;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExtResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetExtResponseBody Body;
        
        public GetExtResponse() {
        }
        
        public GetExtResponse(GtDev.SpeedCamera.ServiceReference.GetExtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExtResult;
        
        public GetExtResponseBody() {
        }
        
        public GetExtResponseBody(string GetExtResult) {
            this.GetExtResult = GetExtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhotoPagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhotoPages", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequestBody Body;
        
        public GetPhotoPagesRequest() {
        }
        
        public GetPhotoPagesRequest(GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhotoPagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Lang;
        
        public GetPhotoPagesRequestBody() {
        }
        
        public GetPhotoPagesRequestBody(int GuidControl, int guid, string Lang) {
            this.GuidControl = GuidControl;
            this.guid = guid;
            this.Lang = Lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhotoPagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhotoPagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.GetPhotoPagesResponseBody Body;
        
        public GetPhotoPagesResponse() {
        }
        
        public GetPhotoPagesResponse(GtDev.SpeedCamera.ServiceReference.GetPhotoPagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhotoPagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPhotoPagesResult;
        
        public GetPhotoPagesResponseBody() {
        }
        
        public GetPhotoPagesResponseBody(string GetPhotoPagesResult) {
            this.GetPhotoPagesResult = GetPhotoPagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddObjectAjaxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddObjectAjax", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequestBody Body;
        
        public AddObjectAjaxRequest() {
        }
        
        public AddObjectAjaxRequest(GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddObjectAjaxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GuidClassifier;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int GuidControl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayValue;
        
        public AddObjectAjaxRequestBody() {
        }
        
        public AddObjectAjaxRequestBody(int GuidClassifier, int GuidControl, GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayName, GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayValue) {
            this.GuidClassifier = GuidClassifier;
            this.GuidControl = GuidControl;
            this.ArrayName = ArrayName;
            this.ArrayValue = ArrayValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddObjectAjaxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddObjectAjaxResponse", Namespace="http://tempuri.org/", Order=0)]
        public GtDev.SpeedCamera.ServiceReference.AddObjectAjaxResponseBody Body;
        
        public AddObjectAjaxResponse() {
        }
        
        public AddObjectAjaxResponse(GtDev.SpeedCamera.ServiceReference.AddObjectAjaxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddObjectAjaxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GtDev.SpeedCamera.ServiceReference.ArrayOfString AddObjectAjaxResult;
        
        public AddObjectAjaxResponseBody() {
        }
        
        public AddObjectAjaxResponseBody(GtDev.SpeedCamera.ServiceReference.ArrayOfString AddObjectAjaxResult) {
            this.AddObjectAjaxResult = AddObjectAjaxResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AjaxSoapChannel : GtDev.SpeedCamera.ServiceReference.AjaxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AjaxSoapClient : System.ServiceModel.ClientBase<GtDev.SpeedCamera.ServiceReference.AjaxSoap>, GtDev.SpeedCamera.ServiceReference.AjaxSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AjaxSoapClient() : 
                base(AjaxSoapClient.GetDefaultBinding(), AjaxSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.AjaxSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AjaxSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AjaxSoapClient.GetBindingForEndpoint(endpointConfiguration), AjaxSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AjaxSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AjaxSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AjaxSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AjaxSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AjaxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetNewPinGraphicsAsync(GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequest request) {
            return base.Channel.GetNewPinGraphicsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsResponse> GetNewPinGraphicsAsync() {
            GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetNewPinGraphicsRequestBody();
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetNewPinGraphicsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.CheckPinGraphicsAsync(GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequest request) {
            return base.Channel.CheckPinGraphicsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsResponse> CheckPinGraphicsAsync(string txt) {
            GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequest inValue = new GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.CheckPinGraphicsRequestBody();
            inValue.Body.txt = txt;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).CheckPinGraphicsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetNewPinAsync(GtDev.SpeedCamera.ServiceReference.GetNewPinRequest request) {
            return base.Channel.GetNewPinAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetNewPinResponse> GetNewPinAsync() {
            GtDev.SpeedCamera.ServiceReference.GetNewPinRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetNewPinRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetNewPinRequestBody();
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetNewPinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.CheckPinAsync(GtDev.SpeedCamera.ServiceReference.CheckPinRequest request) {
            return base.Channel.CheckPinAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.CheckPinResponse> CheckPinAsync(string guid, string txt) {
            GtDev.SpeedCamera.ServiceReference.CheckPinRequest inValue = new GtDev.SpeedCamera.ServiceReference.CheckPinRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.CheckPinRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.txt = txt;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).CheckPinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveVoiteResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.SaveVoiteAsync(GtDev.SpeedCamera.ServiceReference.SaveVoiteRequest request) {
            return base.Channel.SaveVoiteAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveVoiteResponse> SaveVoiteAsync(int GuidObject, string list) {
            GtDev.SpeedCamera.ServiceReference.SaveVoiteRequest inValue = new GtDev.SpeedCamera.ServiceReference.SaveVoiteRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.SaveVoiteRequestBody();
            inValue.Body.GuidObject = GuidObject;
            inValue.Body.list = list;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).SaveVoiteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveForumResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.SaveForumAsync(GtDev.SpeedCamera.ServiceReference.SaveForumRequest request) {
            return base.Channel.SaveForumAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.SaveForumResponse> SaveForumAsync(int GuidControl, int GuidClassifier, int GuidObject, string name, string title, string text, string pin1, string pin2) {
            GtDev.SpeedCamera.ServiceReference.SaveForumRequest inValue = new GtDev.SpeedCamera.ServiceReference.SaveForumRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.SaveForumRequestBody();
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.GuidClassifier = GuidClassifier;
            inValue.Body.GuidObject = GuidObject;
            inValue.Body.name = name;
            inValue.Body.title = title;
            inValue.Body.text = text;
            inValue.Body.pin1 = pin1;
            inValue.Body.pin2 = pin2;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).SaveForumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetCacheResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetCacheAsync(GtDev.SpeedCamera.ServiceReference.GetCacheRequest request) {
            return base.Channel.GetCacheAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetCacheResponse> GetCacheAsync(string NameCache, int GuidControl, object Param1, object Param2, object Param3) {
            GtDev.SpeedCamera.ServiceReference.GetCacheRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetCacheRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetCacheRequestBody();
            inValue.Body.NameCache = NameCache;
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetCacheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetAsync(GtDev.SpeedCamera.ServiceReference.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetResponse> GetAsync(int GuidControl, object Param1, object Param2, object Param3) {
            GtDev.SpeedCamera.ServiceReference.GetRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetRequestBody();
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetExtResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetExtAsync(GtDev.SpeedCamera.ServiceReference.GetExtRequest request) {
            return base.Channel.GetExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetExtResponse> GetExtAsync(int GuidControl, object Param1, object Param2, object Param3) {
            GtDev.SpeedCamera.ServiceReference.GetExtRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetExtRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetExtRequestBody();
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetExtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetPhotoPagesResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.GetPhotoPagesAsync(GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequest request) {
            return base.Channel.GetPhotoPagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.GetPhotoPagesResponse> GetPhotoPagesAsync(int GuidControl, int guid, string Lang) {
            GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequest inValue = new GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.GetPhotoPagesRequestBody();
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.guid = guid;
            inValue.Body.Lang = Lang;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).GetPhotoPagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.AddObjectAjaxResponse> GtDev.SpeedCamera.ServiceReference.AjaxSoap.AddObjectAjaxAsync(GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequest request) {
            return base.Channel.AddObjectAjaxAsync(request);
        }
        
        public System.Threading.Tasks.Task<GtDev.SpeedCamera.ServiceReference.AddObjectAjaxResponse> AddObjectAjaxAsync(int GuidClassifier, int GuidControl, GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayName, GtDev.SpeedCamera.ServiceReference.ArrayOfString ArrayValue) {
            GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequest inValue = new GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequest();
            inValue.Body = new GtDev.SpeedCamera.ServiceReference.AddObjectAjaxRequestBody();
            inValue.Body.GuidClassifier = GuidClassifier;
            inValue.Body.GuidControl = GuidControl;
            inValue.Body.ArrayName = ArrayName;
            inValue.Body.ArrayValue = ArrayValue;
            return ((GtDev.SpeedCamera.ServiceReference.AjaxSoap)(this)).AddObjectAjaxAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.AjaxSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.AjaxSoap)) {
                return new System.ServiceModel.EndpointAddress("http://mvd.gov.by/Ajax.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return AjaxSoapClient.GetBindingForEndpoint(EndpointConfiguration.AjaxSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return AjaxSoapClient.GetEndpointAddress(EndpointConfiguration.AjaxSoap);
        }
        
        public enum EndpointConfiguration {
            
            AjaxSoap,
        }
    }
}
